### PR TITLE
Prevent distributed singletons created during other's init from duping IDs

### LINKED ISSUE #1131: DA spawned by a ClusterSingleton inherits _Props and leads to duplicateActorPath error
I have a cluster singleton (e.g., `Singleton`) that spawns another distributed actor (e.g., `Greeter`) to do some work. 

```swift
distributed actor Singleton: ClusterSingleton {
    typealias ActorSystem = ClusterSystem

    private let greeter: Greeter

    init(actorSystem: ActorSystem) {
        self.actorSystem = actorSystem
        self.greeter = Greeter(actorSystem: actorSystem)
    }
}

distributed actor Greeter {
    typealias ActorSystem = ClusterSystem

    distributed func greet() {
        print("Hello!")
    }
}
```

I have a test that starts the cluster singleton in a single-node cluster like so:

```swift
        let singleton = try await clusterSystem.singleton.host(name: "test-singleton") { actorSystem in
            Singleton(actorSystem: actorSystem)
        }
```

The test crashes with error:

```
DistributedCluster/ClusterSystem.swift:759: Fatal error: 'try!' expression unexpectedly raised an error: ClusterSystemError(duplicateActorPath(path: /user/test-singleton), at: DistributedCluster/Refs.swift:642)
```

Upon inspecting trace logs I see that `Greeter` has inherited the `_Props` of `Singleton`, which results in the two actors having the same id:

```
2023-07-08T11:31:13-0700 trace test : actor/id=[$wellKnown: test-singleton] actor/type=Singleton cluster/node=sact://test@127.0.0.1:9001 [DistributedCluster] Assign identity
2023-07-08T11:31:13-0700 trace test : actor/id=[$wellKnown: test-singleton] actor/type=Greeter cluster/node=sact://test@127.0.0.1:9001 [DistributedCluster] Assign identity
2023-07-08T11:31:13-0700 trace test : actor/id=[$wellKnown: test-singleton] actor/type=Greeter cluster/node=sact://test@127.0.0.1:9001 [DistributedCluster] Actor ready
2023-07-08T11:31:13-0700 trace test : actor/id=[$wellKnown: test-singleton] actor/type=Singleton cluster/node=sact://test@127.0.0.1:9001 [DistributedCluster] Actor ready
```

The error does NOT occur if `Greeter` is initialized inside a distributed func invoked outside:

```swift
distributed actor Singleton: ClusterSingleton {
    typealias ActorSystem = ClusterSystem

    private var greeter: Greeter?

    init(actorSystem: ActorSystem) {
        self.actorSystem = actorSystem
    }
    
    distributed func initGreeter() {
        self.greeter = Greeter(actorSystem: actorSystem)
    }
}

let singleton = try await clusterSystem.singleton.host(name: "test-singleton") { actorSystem in
    Singleton(actorSystem: actorSystem)
}
try await singleton.initGreeter()
```

### PR DESCRIPTION
**Pull request by ktoso**
### Motivation:

We need to "consume" the sneaky way we sneak in the "use this ID" into `assignID`. Without this we'd assign the same ID if someone were to create a singleton DURING the init() of another singleton.

I need to work around a few aggressive assertions that are trying to prevent users doing bad stuff that we actually do want to do here, but this'll work ok.

### Modifications:

We "consume" the "props for spawn" during assignID as it should be. This works because that's code generated as first thing in every distributed actor init.

### Result:

resolves #1131
rdar://112434926

relates to rdar://112433423 which is about a language feature to enable control over this properly.

### CODE REVIEW

File: Sources/DistributedCluster/Cluster/SWIM/ClusterMembership+Converters.swift [hunk 1]
```diff
@@ -29,7 +29,11 @@ extension ClusterMembership.Node {
     }
 
     func swimShell(_ system: ClusterSystem) -> SWIMActor {
-        try! SWIMActor.resolve(id: ._swim(on: self.asClusterNode!), using: system) // TODO: the ! is not so nice
+        do {
+            return try SWIMActor.resolve(id: ._swim(on: self.asClusterNode!), using: system)
+        } catch {
+            fatalError("Failed to resolve \(ActorID._swim(on: self.asClusterNode!).detailedDescription): \(error), tree: \n\(system._treeString())")
```
Comment (ktoso) [inline Sources/DistributedCluster/Cluster/SWIM/ClusterMembership+Converters.swift:35]: Just improving error message, should not happen in real code but helps debug when we mess up assignID ;)

File: Sources/DistributedCluster/ClusterSystem.swift [hunk 2]
```diff
@@ -1101,9 +1119,9 @@ extension ClusterSystem {
     {
         /// Prepare a distributed actor context base, such that the reserved ID will contain the interceptor in the context.
         let baseContext = DistributedActorContext(lifecycle: nil, remoteCallInterceptor: interceptor)
-        var id = self._assignID(Act.self, baseContext: baseContext)
+         var id = self._assignID(Act.self, baseContext: baseContext)
```
Comment (yim-lee) [inline Sources/DistributedCluster/ClusterSystem.swift:1122]: nit: extra space

File: Sources/DistributedCluster/Props.swift [hunk 3]
```diff
@@ -79,11 +90,51 @@ public struct _Props: @unchecked Sendable {
...
+        p._wellKnown = self._wellKnown
+        return p
+    }
+
     /// Allows for passing properties to creating a distributed actor.
     @TaskLocal
     internal static var forSpawn: _Props = .init()
 }
 
+/// INTERNAL: Used for shuttling the Props into the ID while performing assignID.
```
Comment (yim-lee) [inline Sources/DistributedCluster/Props.swift:120]: 👍

File: Tests/DistributedClusterTests/Plugins/ClusterSingleton/ClusterSingletonPluginTests.swift [hunk 4]
```diff
@@ -38,4 +39,57 @@ final class ClusterSingletonPluginTests: SingleClusterSystemXCTestCase {
...
+        }
+
+        let singletonID = singleton.id
+        let greeterID = try await singleton.getGreeter().id
+
+        pinfo("singleton proxy    id: \(singletonID)")
+        pinfo("singleton actual   id: \(try await singleton.actualID())")
+        pinfo("singleton(greeter) id: \(greeterID)")
+
+//        singletonID.detailedDescription.shouldContain("test-singleton")
```
Comment (yim-lee) [inline Tests/DistributedClusterTests/Plugins/ClusterSingleton/ClusterSingletonPluginTests.swift:59]: remove?

**Review by yim-lee — APPROVED** [review]

File: Tests/DistributedClusterTests/Plugins/ClusterSingleton/ClusterSingletonPluginTests.swift (hunk 4 above)
Comment (ktoso) [reply Tests/DistributedClusterTests/Plugins/ClusterSingleton/ClusterSingletonPluginTests.swift:59]: yup thx

File: Sources/DistributedCluster/ClusterSystem.swift (hunk 2 above)
Comment (ktoso) [reply Sources/DistributedCluster/ClusterSystem.swift:1122]: thx, missed formatter run, fixing

**Comment by ktoso** [comment]
Just one of the jobs had a timeout https://github.com/apple/swift-distributed-actors/issues/1133 failure
